name: sql_snowflake
description: ''
version: '2.0'
author: null
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/demo-job:
    name: demo-job
    description: ''
    fabricUID: 2791
    scheduler:
      Prophecy: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: 0 0/1 * * *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: true
    createdAt: '2023-06-23 10:02:57'
    author: poojas+2@prophecy.io
functions:
  author: null
  createdAt: '2023-06-23 06:43:28'
  gems: {}
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/Failed_orders:
    name: Failed_orders
    schema:
      providerType: Snowflake
      fields:
      - name: STATUS
        dataType:
          type: String
      - name: ORDER_DATE
        dataType:
          type: Date
      - name: LAST_NAME
        dataType:
          type: String
      - name: FIRST_NAME
        dataType:
          type: String
      - name: ORDER_ID
        dataType:
          type: Number
      - name: CUSTOMER_ID
        dataType:
          type: Number
      - name: PAYMENTMETHOD
        dataType:
          type: String
      - name: PAYMENT_STATUS
        dataType:
          type: String
      - name: AMOUNT
        dataType:
          type: Number
    description: null
    author: poojas+2@prophecy.io
    files:
    - models/Failed_orders.sql
    - .prophecy/ide/models/Failed_orders.json
    sqlDependencies:
      models: []
      datasets: []
    createdAt: '2023-06-23 07:07:15'
sqlMacros: {}
sqlSeeds: {}
sqlSources:
  .prophecy/metadata/sqlsources/POOJA_JAFFLE_SHOP:
    name: POOJA.JAFFLE_SHOP
    description: null
    author: poojas+2@prophecy.io
    files:
    - prophecy-sources/sources.yml
    createdAt: '2023-06-23 06:54:34'
    tables:
    - name: CUSTOMERS
      schema:
        providerType: snowflake
        fields:
        - name: ORDER_ID
          dataType:
            type: Number
        - name: ORDER_DATE
          dataType:
            type: Date
        - name: STATUS
          dataType:
            type: String
        - name: FIRST_NAME
          dataType:
            type: String
        - name: LAST_NAME
          dataType:
            type: String
        - name: CUSTOMER_ID
          dataType:
            type: Number
      description: null
      author: poojas+2@prophecy.io
      createdAt: '2023-06-23 06:54:34'
    - name: ORDERS
      schema:
        providerType: snowflake
        fields:
        - name: ID
          dataType:
            type: Number
        - name: USER_ID
          dataType:
            type: Number
        - name: ORDER_DATE
          dataType:
            type: Date
        - name: STATUS
          dataType:
            type: String
        - name: _ETL_LOADED_AT
          dataType:
            type: Timestamp
      description: null
      author: poojas+2@prophecy.io
      createdAt: '2023-06-23 06:54:48'
  .prophecy/metadata/sqlsources/POOJA_STRIPE:
    name: POOJA.STRIPE
    description: null
    author: poojas+2@prophecy.io
    files:
    - prophecy-sources/sources.yml
    createdAt: '2023-06-23 06:56:08'
    tables:
    - name: PAYMENT
      schema:
        providerType: snowflake
        fields:
        - name: ID
          dataType:
            type: Number
        - name: ORDERID
          dataType:
            type: Number
        - name: PAYMENTMETHOD
          dataType:
            type: String
        - name: STATUS
          dataType:
            type: String
        - name: AMOUNT
          dataType:
            type: Number
        - name: CREATED
          dataType:
            type: Date
        - name: _BATCHED_AT
          dataType:
            type: Timestamp
      description: null
      author: poojas+2@prophecy.io
      createdAt: '2023-06-23 06:56:08'
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: poojas+2@prophecy.io
  createdAt: '2023-06-23 06:43:28'
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
