
version: 2
sources:
- name: "spark_catalog.anya"
  database: "spark_catalog"
  schema: "anya"
  config:
    enabled: true
  tables:
  - name: "reportscd1"
    columns:
    - name: "Name"
      dataType:
        type: "String"
    - name: "Income"
      dataType:
        type: "Bigint"
    - name: "LoanTotal"
      dataType:
        type: "Bigint"
    - name: "FicoScore"
      dataType:
        type: "Bigint"
    - name: "FicoValidFrom"
      dataType:
        type: "Date"
    - name: "FicoValidTo"
      dataType:
        type: "Date"
    - name: "minFlag"
      dataType:
        type: "Boolean"
    - name: "maxFlag"
      dataType:
        type: "Boolean"
    - name: "previousFicoScore"
      dataType:
        type: "Bigint"
    - name: "DTIpercentage"
      dataType:
        type: "Decimal"
  - name: "reportscd2"
    columns:
    - name: "Name"
      dataType:
        type: "String"
    - name: "Income"
      dataType:
        type: "Bigint"
    - name: "LoanTotal"
      dataType:
        type: "Bigint"
    - name: "FicoScore"
      dataType:
        type: "Bigint"
    - name: "FicoValidFrom"
      dataType:
        type: "Date"
    - name: "FicoValidTo"
      dataType:
        type: "Date"
    - name: "minFlag"
      dataType:
        type: "Boolean"
    - name: "maxFlag"
      dataType:
        type: "Boolean"
    - name: "previousFicoScore"
      dataType:
        type: "Bigint"
    - name: "DTIpercentage"
      dataType:
        type: "Decimal"
- name: "samples.tpch"
  database: "samples"
  schema: "tpch"
  config:
    enabled: true
  tables:
  - name: "customer"
    columns:
    - name: "c_custkey"
      dataType:
        type: "Bigint"
    - name: "c_name"
      dataType:
        type: "String"
    - name: "c_address"
      dataType:
        type: "String"
    - name: "c_nationkey"
      dataType:
        type: "Bigint"
    - name: "c_phone"
      dataType:
        type: "String"
    - name: "c_acctbal"
      dataType:
        type: "Decimal"
    - name: "c_mktsegment"
      dataType:
        type: "String"
    - name: "c_comment"
      dataType:
        type: "String"
  - name: "nation"
    columns:
    - name: "n_nationkey"
      dataType:
        type: "Bigint"
    - name: "n_name"
      dataType:
        type: "String"
    - name: "n_regionkey"
      dataType:
        type: "Bigint"
    - name: "n_comment"
      dataType:
        type: "String"
- name: "hive_metastore.default"
  database: "hive_metastore"
  schema: "default"
  config:
    enabled: true
  tables:
  - name: "test_model"
    columns:
    - name: "c_custkey"
      dataType:
        type: "Bigint"
    - name: "c_name"
      dataType:
        type: "String"
    - name: "c_address"
      dataType:
        type: "String"
    - name: "c_nationkey"
      dataType:
        type: "Bigint"
    - name: "c_phone"
      dataType:
        type: "String"
    - name: "c_acctbal"
      dataType:
        type: "Decimal"
    - name: "c_mktsegment"
      dataType:
        type: "String"
    - name: "c_comment"
      dataType:
        type: "String"
    - name: "n_nationkey"
      dataType:
        type: "Bigint"
    - name: "n_name"
      dataType:
        type: "String"
    - name: "n_regionkey"
      dataType:
        type: "Bigint"
    - name: "n_comment"
      dataType:
        type: "String"
