WITH ORDERS AS (

  SELECT * 
  
  FROM {{ source('POOJA.JAFFLE_SHOP', 'ORDERS') }}

),

CUSTOMERS AS (

  SELECT * 
  
  FROM {{ source('POOJA.JAFFLE_SHOP', 'CUSTOMERS') }}

),

Join_1 AS (

  SELECT 
    ORDERS.ID AS ID,
    ORDERS.USER_ID AS USER_ID,
    ORDERS._ETL_LOADED_AT AS _ETL_LOADED_AT,
    CUSTOMERS.STATUS AS STATUS,
    CUSTOMERS.ORDER_DATE AS ORDER_DATE,
    CUSTOMERS.LAST_NAME AS LAST_NAME,
    CUSTOMERS.FIRST_NAME AS FIRST_NAME,
    CUSTOMERS.ORDER_ID AS ORDER_ID,
    CUSTOMERS.CUSTOMER_ID AS CUSTOMER_ID
  
  FROM CUSTOMERS
  INNER JOIN ORDERS
     ON CUSTOMERS.ORDER_ID = ORDERS.ID

),

Reformat_1 AS (

  SELECT 
    STATUS AS STATUS,
    ORDER_DATE AS ORDER_DATE,
    LAST_NAME AS LAST_NAME,
    FIRST_NAME AS FIRST_NAME,
    ORDER_ID AS ORDER_ID,
    CUSTOMER_ID AS CUSTOMER_ID
  
  FROM Join_1 AS in0

),

PAYMENT AS (

  SELECT * 
  
  FROM {{ source('POOJA.STRIPE', 'PAYMENT') }}

),

Join_2 AS (

  SELECT 
    in0.STATUS AS STATUS,
    in0.ORDER_DATE AS ORDER_DATE,
    in0.LAST_NAME AS LAST_NAME,
    in0.FIRST_NAME AS FIRST_NAME,
    in0.ORDER_ID AS ORDER_ID,
    in0.CUSTOMER_ID AS CUSTOMER_ID,
    in1.PAYMENTMETHOD AS PAYMENTMETHOD,
    in1.STATUS AS PAYMENT_STATUS,
    in1.AMOUNT AS AMOUNT
  
  FROM Reformat_1 AS in0
  INNER JOIN PAYMENT AS in1
     ON in0.ORDER_ID = in1.ORDERID

),

Filter_1 AS (

  SELECT * 
  
  FROM Join_2 AS in0
  
  WHERE in0.PAYMENT_STATUS = 'fail' AND in0.STATUS = 'completed'

)

SELECT *

FROM Filter_1
